# All Clusters
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-apiserver
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: development
      values:
        branch: development
        project: development-cluster-config
        path: '{{name}}'
  - clusters:
      selector:
        matchLabels:
          environment: preproduction
          sox: "false"
      values:
        branch: main
        project: preproduction-cluster-config
        path: '{{name}}'
  - clusters:
      selector:
        matchLabels:
          environment: production
        matchExpressions:
          - { key: sox, operator: NotIn, values: ["true"] }
      values:
        branch: main
        project: production-cluster-config
        path: '{{name}}'
  - clusters:
      selector:
        matchExpressions:
          - { key: sox, operator: In, values: ["true"] }
      values:
        branch: main
        project: default
        path: sox
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{name}}-apiserver'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: https://github.com/GitOps-FromGitGenerator-To-ClusterLabel/cluster-config.git
        targetRevision: '{{values.branch}}'
        path: apiserver/overlays/{{values.path}}
      destination:
        server: '{{server}}'
      syncPolicy: {}
      revisionHistoryLimit: 5
