# All in one ApplicationSet, with the Cluster Selector and the additional key-value section
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-htpasswd
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: development
      values:
        project: default
        branch: main
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{name}}-htpasswd'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: https://github.com/GitOps-FromGitGenerator-To-ClusterLabel/cluster-config.git
        targetRevision: '{{values.branch}}'
        path: htpasswd/overlays/{{name}}
      destination:
        server: '{{server}}'
      syncPolicy: {}
      revisionHistoryLimit: 5
