# Actual Git Generator
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-cluster-management-observability
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/GitOps-FromGitGenerator-To-ClusterLabel/bootstrap.git
      revision: main
      files:
      - path: "cluster-definition/local-cluster/cluster.json"
  template:
    metadata:
      name: '{{cluster.name}}-open-cluster-management-observability'
    spec:
      project: observability
      source:
        repoURL: https://github.com/GitOps-FromGitGenerator-To-ClusterLabel/cluster-config.git
        targetRevision: main
        path: observability
      destination:
        server: '{{cluster.address}}'
      syncPolicy: {}

# Moving to Cluster Selector as Generator
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: open-cluster-management-observability
#   namespace: openshift-gitops
# spec:
#   generators:
#   - clusters:
#       selector:
#         matchLabels:
#           environment: acm-production
#           usage: acm-hub
#   template:
#     metadata:
#       name: '{{name}}-open-cluster-management-observability'
#     spec:
#       project: observability
#       source:
#         repoURL: https://github.com/GitOps-FromGitGenerator-To-ClusterLabel/cluster-config.git
#         targetRevision: main
#         path: observability
#       destination:
#         server: '{{server}}'
#       syncPolicy: {}
